using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Rebel.Infrastructure.Migrations
{
    [Microsoft.EntityFrameworkCore.Infrastructure.DbContext(typeof(global::Rebel.Infrastructure.Data.AppDbContext))]
    [Migration("20260722123000_AddReservationActivities")]
    public partial class AddReservationActivities : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "ReservationActivities" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "ReservationId" uuid NOT NULL,
                    "Title" character varying(80) NOT NULL,
                    "Description" character varying(500) NOT NULL,
                    "Actor" character varying(30) NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_ReservationActivities" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_ReservationActivities_Reservations_ReservationId"
                        FOREIGN KEY ("ReservationId") REFERENCES "Reservations" ("Id")
                        ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_ReservationActivities_ReservationId_CreatedAtUtc"
                    ON "ReservationActivities" ("ReservationId", "CreatedAtUtc");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ReservationActivities");
        }
    }
}
