using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Rebel.Infrastructure.Data;
using Rebel.Web.Services;
using Rebel.Web.Hubs;
using Rebel.Web.Authorization;

var builder = WebApplication.CreateBuilder(args);

var defaultConnection =
    builder.Configuration.GetConnectionString("DefaultConnection")
    ?? throw new InvalidOperationException(
        "DefaultConnection is missing from configuration.");

if (builder.Environment.IsProduction() &&
    defaultConnection.Contains(
        "CHANGE_ME",
        StringComparison.OrdinalIgnoreCase))
{
    throw new InvalidOperationException(
        "Production database connection string still contains CHANGE_ME.");
}

builder.Services.AddControllersWithViews();
builder.Services.AddSignalR();
builder.Services.AddScoped<IBeerRecommendationService, BeerRecommendationService>();
builder.Services.AddScoped<IBeerGuideNarrator, OpenAiBeerGuideNarrator>();
builder.Services.AddSingleton<IBeerCatalogMatcher, BeerCatalogMatcher>();
builder.Services.AddSingleton<IFoodCatalogMatcher, FoodCatalogMatcher>();
builder.Services.AddSingleton<IBeerPreferenceParser, BeerPreferenceParser>();
builder.Services.AddSingleton<IBeerConversationQueryBuilder, BeerConversationQueryBuilder>();
builder.Services.AddSingleton<IBeerChatStateService, BeerChatStateService>();
builder.Services.AddSingleton<IBeerFeedbackLearningService, BeerFeedbackLearningService>();
builder.Services.AddSingleton<IBeerGuideTestLabService, BeerGuideTestLabService>();
builder.Services.AddSingleton<IBeerProfileSuggestionService, BeerProfileSuggestionService>();
builder.Services.AddSingleton<IBeerProfileReviewQueueService, BeerProfileReviewQueueService>();
builder.Services.AddSingleton<IBeerNoMatchRecoveryService, BeerNoMatchRecoveryService>();
builder.Services.AddScoped<IBeerGuideChatService, OpenAiBeerGuideChatService>();

builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(
        defaultConnection
    )
);

builder.Services.AddDefaultIdentity<IdentityUser>(options =>
{
    options.SignIn.RequireConfirmedAccount = false;
})
.AddRoles<IdentityRole>()
.AddEntityFrameworkStores<AppDbContext>();

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy(
        AdminPolicies.Backstage,
        policy => policy.RequireRole(
            AdminRoles.LegacyAdmin,
            AdminRoles.Manager,
            AdminRoles.Staff));

    options.AddPolicy(
        AdminPolicies.ManagerOnly,
        policy => policy.RequireRole(
            AdminRoles.LegacyAdmin,
            AdminRoles.Manager));
});

// EMAIL SETTINGS
builder.Services.Configure<EmailSettings>(
    builder.Configuration.GetSection("EmailSettings")
);

// EMAIL SERVICE
builder.Services.AddScoped<IEmailService, EmailService>();

var app = builder.Build();

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}"
);

app.MapRazorPages();

using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;

    var dbContext =
        services.GetRequiredService<AppDbContext>();

    await dbContext.Database.MigrateAsync();

    await dbContext.Database.ExecuteSqlRawAsync(
        """
        ALTER TABLE "Reservations"
        ADD COLUMN IF NOT EXISTS "InternalNote"
            character varying(500);

        ALTER TABLE "Reservations"
        ADD COLUMN IF NOT EXISTS "TableLabel"
            character varying(40);

        ALTER TABLE "Reservations"
        ADD COLUMN IF NOT EXISTS "ReservationCode"
            character varying(16) NOT NULL DEFAULT '';

        UPDATE "Reservations"
        SET "ReservationCode" =
            'RR-' ||
            upper(
                substring(
                    replace("Id"::text, '-', ''),
                    1,
                    6
                )
            )
        WHERE "ReservationCode" = '';

        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Reservations_ReservationCode"
            ON "Reservations" ("ReservationCode");

        ALTER TABLE "Reservations"
        ADD COLUMN IF NOT EXISTS "EmailStatus"
            character varying(30) NOT NULL DEFAULT 'NotSent';

        ALTER TABLE "Reservations"
        ADD COLUMN IF NOT EXISTS "LastEmailSentAtUtc"
            timestamp with time zone;

        ALTER TABLE "Reservations"
        ADD COLUMN IF NOT EXISTS "LastEmailError"
            character varying(500);

        CREATE TABLE IF NOT EXISTS "ReservationActivities" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "ReservationId" uuid NOT NULL,
            "Title" character varying(80) NOT NULL,
            "Description" character varying(500) NOT NULL,
            "Actor" character varying(30) NOT NULL,
            "CreatedAtUtc" timestamp with time zone NOT NULL,
            CONSTRAINT "PK_ReservationActivities" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_ReservationActivities_Reservations_ReservationId"
                FOREIGN KEY ("ReservationId") REFERENCES "Reservations" ("Id")
                ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS "IX_ReservationActivities_ReservationId_CreatedAtUtc"
            ON "ReservationActivities" ("ReservationId", "CreatedAtUtc");

        ALTER TABLE "Events"
        ADD COLUMN IF NOT EXISTS "MaxGuests"
            integer;

        ALTER TABLE "Events"
        ADD COLUMN IF NOT EXISTS "MaxReservations"
            integer;

        ALTER TABLE "Products"
        ADD COLUMN IF NOT EXISTS "ContainsNuts"
            boolean NOT NULL DEFAULT FALSE;

        ALTER TABLE "Products"
        ADD COLUMN IF NOT EXISTS "IsGlutenFree"
            boolean NOT NULL DEFAULT FALSE;

        ALTER TABLE "Products"
        ADD COLUMN IF NOT EXISTS "IsLimited"
            boolean NOT NULL DEFAULT FALSE;

        ALTER TABLE "Products"
        ADD COLUMN IF NOT EXISTS "IsPopular"
            boolean NOT NULL DEFAULT FALSE;

        ALTER TABLE "Products"
        ADD COLUMN IF NOT EXISTS "IsPromo"
            boolean NOT NULL DEFAULT FALSE;

        ALTER TABLE "Products"
        ADD COLUMN IF NOT EXISTS "IsSpicy"
            boolean NOT NULL DEFAULT FALSE;

        ALTER TABLE "Products"
        ADD COLUMN IF NOT EXISTS "IsVegan"
            boolean NOT NULL DEFAULT FALSE;

        ALTER TABLE "Products"
        ADD COLUMN IF NOT EXISTS "IsVegetarian"
            boolean NOT NULL DEFAULT FALSE;

        ALTER TABLE "Categories"
        ADD COLUMN IF NOT EXISTS "IsDeleted"
            boolean NOT NULL DEFAULT FALSE;

        ALTER TABLE "Categories"
        ADD COLUMN IF NOT EXISTS "DeletedAtUtc"
            timestamp with time zone;

        ALTER TABLE "Events"
        ADD COLUMN IF NOT EXISTS "IsDeleted"
            boolean NOT NULL DEFAULT FALSE;

        ALTER TABLE "Events"
        ADD COLUMN IF NOT EXISTS "DeletedAtUtc"
            timestamp with time zone;

        ALTER TABLE "Products"
        ADD COLUMN IF NOT EXISTS "IsDeleted"
            boolean NOT NULL DEFAULT FALSE;

        ALTER TABLE "Products"
        ADD COLUMN IF NOT EXISTS "DeletedAtUtc"
            timestamp with time zone;

        ALTER TABLE "Reservations"
        ADD COLUMN IF NOT EXISTS "IsDeleted"
            boolean NOT NULL DEFAULT FALSE;

        ALTER TABLE "Reservations"
        ADD COLUMN IF NOT EXISTS "DeletedAtUtc"
            timestamp with time zone;

        CREATE TABLE IF NOT EXISTS "PubTables" (
            "Id" uuid NOT NULL,
            "Label" character varying(40) NOT NULL,
            "Area" character varying(80) NULL,
            "Capacity" integer NOT NULL,
            "IsActive" boolean NOT NULL,
            CONSTRAINT "PK_PubTables" PRIMARY KEY ("Id")
        );

        CREATE UNIQUE INDEX IF NOT EXISTS "IX_PubTables_Label"
            ON "PubTables" ("Label");

        CREATE TABLE IF NOT EXISTS "StaffMembers" (
            "Id" uuid NOT NULL,
            "FullName" character varying(80) NOT NULL,
            "Role" character varying(20) NOT NULL,
            "PhoneNumber" character varying(40) NULL,
            "IsActive" boolean NOT NULL,
            CONSTRAINT "PK_StaffMembers" PRIMARY KEY ("Id")
        );

        CREATE INDEX IF NOT EXISTS "IX_StaffMembers_IsActive_Role"
            ON "StaffMembers" ("IsActive", "Role");

        CREATE TABLE IF NOT EXISTS "StaffShifts" (
            "Id" uuid NOT NULL,
            "StaffMemberId" uuid NOT NULL,
            "Role" character varying(20) NOT NULL,
            "ShiftDate" date NOT NULL,
            "StartsAt" time without time zone NOT NULL,
            "EndsAt" time without time zone NOT NULL,
            "Note" character varying(160) NULL,
            "CreatedAtUtc" timestamp with time zone NOT NULL,
            CONSTRAINT "PK_StaffShifts" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_StaffShifts_StaffMembers_StaffMemberId"
                FOREIGN KEY ("StaffMemberId") REFERENCES "StaffMembers" ("Id")
                ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS "IX_StaffShifts_ShiftDate_Role"
            ON "StaffShifts" ("ShiftDate", "Role");

        CREATE INDEX IF NOT EXISTS "IX_StaffShifts_StaffMemberId"
            ON "StaffShifts" ("StaffMemberId");

        UPDATE "StaffMembers"
        SET "Role" = 'Front'
        WHERE "Role" IN ('Manager', 'Waiter', 'Bar');

        UPDATE "StaffShifts"
        SET "Role" = 'Front'
        WHERE "Role" IN ('Manager', 'Waiter', 'Bar');

        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_indexes
                WHERE schemaname = 'public'
                    AND indexname = 'IX_Reservations_ReservationDate_ReservationTime_TableLabel'
            )
            AND NOT EXISTS (
                SELECT 1
                FROM "Reservations"
                WHERE "TableLabel" IS NOT NULL
                    AND "Status" IN ('Approved', 'Arrived')
                GROUP BY "ReservationDate", "ReservationTime", "TableLabel"
                HAVING COUNT(*) > 1
            )
            THEN
                CREATE UNIQUE INDEX "IX_Reservations_ReservationDate_ReservationTime_TableLabel"
                    ON "Reservations"
                        ("ReservationDate", "ReservationTime", "TableLabel")
                    WHERE "TableLabel" IS NOT NULL
                        AND "Status" IN ('Approved', 'Arrived');
            END IF;
        END $$;
        """
    );

    var userManager =
        services.GetRequiredService<UserManager<IdentityUser>>();

    var roleManager =
        services.GetRequiredService<RoleManager<IdentityRole>>();

    var adminEmail = app.Configuration["AdminUser:Email"]
    ?? throw new InvalidOperationException(
        "AdminUser:Email is missing from configuration.");

    var adminPassword = app.Configuration["AdminUser:Password"]
        ?? throw new InvalidOperationException(
            "AdminUser:Password is missing from configuration.");

    foreach (var roleName in new[]
    {
        AdminRoles.LegacyAdmin,
        AdminRoles.Manager,
        AdminRoles.Staff
    })
    {
        if (!await roleManager.RoleExistsAsync(roleName))
        {
            await roleManager.CreateAsync(new IdentityRole(roleName));
        }
    }

    var adminUser =
        await userManager.FindByEmailAsync(adminEmail);

    if (adminUser == null)
    {
        adminUser = new IdentityUser
        {
            UserName = adminEmail,
            Email = adminEmail,
            EmailConfirmed = true
        };

        var result = await userManager.CreateAsync(
            adminUser,
            adminPassword
        );

        if (result.Succeeded)
        {
            await userManager.AddToRoleAsync(
                adminUser,
                AdminRoles.LegacyAdmin
            );
        }
    }

    if (adminUser != null &&
        !await userManager.IsInRoleAsync(adminUser, AdminRoles.Manager))
    {
        await userManager.AddToRoleAsync(adminUser, AdminRoles.Manager);
    }
}
app.MapHub<NotificationHub>("/notificationHub");

app.Run();
